[theme]
primaryColor             = "#00478d"
backgroundColor          = "#f8f9ff"
secondaryBackgroundColor = "#f1f3fc"
textColor                = "#181c22"
font                     = "sans serif"

[server]
port = 8504
headless = true
